Fixed comp
willsheffler/rpxdock pull request #33
Opened 2021-09-09 18:40 UTC by mlangow2

Made changes to allow for cart_nstep and ang_step to scale during fixed_wiggle docking.

2021-09-10 18:54 UTC, akhmelin requested changes
if this file is empty, can we delete it? `rpxdock/fragments/ball_joint.py`

2021-09-10 18:54 UTC, akhmelin commented on environment.yml
>   - pandas=0.24.2
can you add this in here? then I don't need to open a commit for it...
` - pyyaml`

2021-09-10 18:54 UTC, akhmelin commented on ide/compile_file.py
> +   main()
sooo what is all this about? this is a hardcoded path to Will's directory, which is all fine for whomever is working in the IPD but will not work for the rest of the world..

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/app/options.py
> +          help='center coorinates from pdb input files')
typo in coordinates

is this for the very lazy people? :D

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/app/options.py
line 319-320 is repetition of lines 322-323

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/app/pilot/helix_beta.py
> +                       help='two structs with configuration to sample around')
be a little more descriptive please, from this help I have no idea what you are talking about (:

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/app/pilot/helix_beta.py
> +
which dimer??

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/fragments/extract_fragments.py
> +
these dependancies will not work anywhere else either. Is there additional db that we should be sharing beyond the ones that are currently in the outwards folder?

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/search/onecomp.py
> +
how many times do we have this repeated?? let's clean up!

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/tests/search/test_cyclic.py
> +   assert 0
not sure that the debug_marisa should be in the main branch

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/search/multicomp.py
> +   components_already_aligned_to_sym_axes=False,
I don't see this change in the options file?

2021-09-10 18:54 UTC, akhmelin commented on rpxdock/tests/search/test_onecomp.py
>  def test_deepesh_1comp_bug(hscore):
would suggest deleting these specific debugging tests

2021-09-10 18:55 UTC, akhmelin commented
this has way more changes then what is described in the commit...

2021-09-11 16:09 UTC, erincyang commented
Mark, I think you have to pull master into your current branch and rerun pytest to resolve all of these comments Alena is pointing out.

2021-09-11 16:44 UTC, mlangow2 commented
I did pull master but didn't now I had to run a pytest, thanks for the heads up. Will get to it when I'm back tomorrow!

2021-09-16 15:04 UTC, akhmelin reviewed
I believe this did not change anything, at least I don't see any changes in the files..?

2021-10-07 04:57 UTC, closed without merging